package electory.client.audio.modplug;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Structure.FieldOrder;
/**
 * <i>native declaration : line 32</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@FieldOrder({"Note", "Instrument", "VolumeEffect", "Effect", "Volume", "Parameter"})
public class ModPlugNote extends Structure {
	public byte Note;
	public byte Instrument;
	public byte VolumeEffect;
	public byte Effect;
	public byte Volume;
	public byte Parameter;
	
	public ModPlugNote() {
		super();
	}
	
	public ModPlugNote(byte Note, byte Instrument, byte VolumeEffect, byte Effect, byte Volume, byte Parameter) {
		super();
		this.Note = Note;
		this.Instrument = Instrument;
		this.VolumeEffect = VolumeEffect;
		this.Effect = Effect;
		this.Volume = Volume;
		this.Parameter = Parameter;
	}
	
	public ModPlugNote(Pointer peer) {
		super(peer);
	}
}
